baseURL = 'https://daluar657.github.io/space-debris-events/'
languageCode = 'en-us'
title = 'Conferences on Space Debris, SSA and STM'

theme = "hugo-bearblog"

[security]
  enableInlineShortcodes = true

[params]
favicon = "images/favicon.png"
lastUpdate = "2026-08-13T00:00:00"
githubURL = "https://github.com/daluar657/space-debris-events"
githubURLIssue = "https://github.com/daluar657/space-debris-events/issues/new?template=11-new-conference.md"
